"""baseline schema

Revision ID: b292dd67bc2d
Revises: 
Created: 2026-08-20 04:28:31.389952
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b292dd67bc2d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OAuthState',
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('userId', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), server_default=sa.text("'integration'"), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('codeVerifier', sa.Text(), nullable=False),
    sa.Column('redirectUri', sa.Text(), nullable=False),
    sa.Column('nonce', sa.Text(), nullable=True),
    sa.Column('nextPath', sa.Text(), nullable=True),
    sa.Column('consumedAt', sa.DateTime(), nullable=True),
    sa.Column('expiresAt', sa.DateTime(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('state', name=op.f('OAuthState_pkey'))
    )
    op.create_index('OAuthState_expiresAt_idx', 'OAuthState', ['expiresAt'], unique=False)
    op.create_table('User',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('passwordHash', sa.Text(), nullable=True),
    sa.Column('passwordUpdatedAt', sa.DateTime(), nullable=True),
    sa.Column('onboardingCompletedAt', sa.DateTime(), nullable=True),
    sa.Column('onboardingSkipped', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deletionRequestedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('User_pkey'))
    )
    op.create_index('User_email_key', 'User', ['email'], unique=True)
    op.create_table('AuthIdentity',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('providerAccountId', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('avatarUrl', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastLoginAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('AuthIdentity_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('AuthIdentity_pkey'))
    )
    op.create_index('AuthIdentity_provider_providerAccountId_key', 'AuthIdentity', ['provider', 'providerAccountId'], unique=True)
    op.create_index('AuthIdentity_userId_idx', 'AuthIdentity', ['userId'], unique=False)
    op.create_table('BrdDocument',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFTING', 'READY', 'FAILED', name='BrdStatus'), server_default=sa.text("'DRAFTING'"), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('lastError', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('BrdDocument_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('BrdDocument_pkey'))
    )
    op.create_index('BrdDocument_userId_createdAt_idx', 'BrdDocument', ['userId', 'createdAt'], unique=False)
    op.create_table('CalendarBusyBlock',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('startsAt', sa.DateTime(), nullable=False),
    sa.Column('endsAt', sa.DateTime(), nullable=False),
    sa.Column('kind', sa.Enum('BUSY', 'FOCUS', 'LUNCH', 'OOO', name='BusyKind'), server_default=sa.text("'BUSY'"), nullable=False),
    sa.Column('source', sa.Text(), server_default=sa.text("'seed'"), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('CalendarBusyBlock_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('CalendarBusyBlock_pkey'))
    )
    op.create_index('CalendarBusyBlock_userId_startsAt_idx', 'CalendarBusyBlock', ['userId', 'startsAt'], unique=False)
    op.create_table('Credential',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('module', sa.Enum('TRANSCRIPTION', 'EXTRACTION', 'TRANSLATION', 'EMBEDDING', 'INTEGRATION', name='CredentialModule'), nullable=False),
    sa.Column('service', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('secretsEnc', sa.Text(), nullable=False),
    sa.Column('hints', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.Enum('UNVERIFIED', 'VALID', 'INVALID', name='CredentialStatus'), server_default=sa.text("'UNVERIFIED'"), nullable=False),
    sa.Column('lastVerifiedAt', sa.DateTime(), nullable=True),
    sa.Column('lastError', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('Credential_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Credential_pkey'))
    )
    op.create_index('Credential_userId_module_idx', 'Credential', ['userId', 'module'], unique=False)
    op.create_index('Credential_userId_service_key', 'Credential', ['userId', 'service'], unique=True)
    op.create_table('IntegrationAccount',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('externalAccountId', sa.Text(), nullable=True),
    sa.Column('accountLabel', sa.Text(), nullable=True),
    sa.Column('scopes', sa.ARRAY(sa.Text()), server_default=sa.text('ARRAY[]::text[]'), nullable=True),
    sa.Column('accessTokenEnc', sa.Text(), nullable=True),
    sa.Column('refreshTokenEnc', sa.Text(), nullable=True),
    sa.Column('expiresAt', sa.DateTime(), nullable=True),
    sa.Column('needsReauth', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('connectedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('IntegrationAccount_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('IntegrationAccount_pkey'))
    )
    op.create_index('IntegrationAccount_userId_provider_key', 'IntegrationAccount', ['userId', 'provider'], unique=True)
    op.create_table('PasswordResetToken',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('tokenHash', sa.Text(), nullable=False),
    sa.Column('expiresAt', sa.DateTime(), nullable=False),
    sa.Column('consumedAt', sa.DateTime(), nullable=True),
    sa.Column('requestedIp', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('PasswordResetToken_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('PasswordResetToken_pkey'))
    )
    op.create_index('PasswordResetToken_expiresAt_idx', 'PasswordResetToken', ['expiresAt'], unique=False)
    op.create_index('PasswordResetToken_tokenHash_key', 'PasswordResetToken', ['tokenHash'], unique=True)
    op.create_index('PasswordResetToken_userId_createdAt_idx', 'PasswordResetToken', ['userId', 'createdAt'], unique=False)
    op.create_table('TeamMember',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('TeamMember_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('TeamMember_pkey'))
    )
    op.create_index('TeamMember_userId_email_key', 'TeamMember', ['userId', 'email'], unique=True)
    op.create_index('TeamMember_userId_name_idx', 'TeamMember', ['userId', 'name'], unique=False)
    op.create_table('Transcript',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('sourceType', sa.Enum('UPLOAD', 'MICROPHONE', 'URL', 'TEAMS', 'MEET', name='TranscriptSource'), server_default=sa.text("'UPLOAD'"), nullable=False),
    sa.Column('sourceUri', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('durationMs', sa.Integer(), nullable=True),
    sa.Column('recordedAt', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'READY', 'FAILED', name='TranscriptStatus'), server_default=sa.text("'READY'"), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('stage', sa.Text(), server_default=sa.text("'done'"), nullable=False),
    sa.Column('progress', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('transcribeError', sa.Text(), nullable=True),
    sa.Column('extractError', sa.Text(), nullable=True),
    sa.Column('extractErrorCode', sa.Text(), nullable=True),
    sa.Column('extractModel', sa.Text(), nullable=True),
    sa.Column('transcribedAt', sa.DateTime(), nullable=True),
    sa.Column('extractedAt', sa.DateTime(), nullable=True),
    sa.Column('transcribeProvider', sa.Text(), nullable=True),
    sa.Column('extractProvider', sa.Text(), nullable=True),
    sa.Column('diarized', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('Transcript_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Transcript_pkey'))
    )
    op.create_index('Transcript_userId_createdAt_idx', 'Transcript', ['userId', 'createdAt'], unique=False)
    op.create_index('Transcript_userId_status_idx', 'Transcript', ['userId', 'status'], unique=False)
    op.create_table('UserSettings',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('timeZone', sa.Text(), server_default=sa.text("'Asia/Kolkata'"), nullable=False),
    sa.Column('workdayStart', sa.Text(), server_default=sa.text("'09:00'"), nullable=False),
    sa.Column('workdayEnd', sa.Text(), server_default=sa.text("'18:00'"), nullable=False),
    sa.Column('allowWeekends', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('maxMeetingMinutes', sa.Integer(), server_default=sa.text('120'), nullable=False),
    sa.Column('minBufferMinutes', sa.Integer(), server_default=sa.text('15'), nullable=False),
    sa.Column('orgDomains', sa.ARRAY(sa.Text()), server_default=sa.text('ARRAY[]::text[]'), nullable=True),
    sa.Column('autoExecuteLowRisk', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('budgetApprovalLimit', sa.Integer(), server_default=sa.text('1000'), nullable=False),
    sa.Column('orgCurrency', sa.Text(), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('approvalThresholds', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('providerRouting', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('UserSettings_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('UserSettings_pkey'))
    )
    op.create_index('UserSettings_userId_key', 'UserSettings', ['userId'], unique=True)
    op.create_table('ActionItem',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('transcriptId', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('actionType', sa.Enum('CALENDAR', 'TASK', 'EMAIL', 'REMINDER', 'NONE', name='ActionType'), server_default=sa.text("'NONE'"), nullable=False),
    sa.Column('ownerName', sa.Text(), nullable=True),
    sa.Column('ownerEmail', sa.Text(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='Priority'), server_default=sa.text("'MEDIUM'"), nullable=False),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='Confidence'), server_default=sa.text("'MEDIUM'"), nullable=False),
    sa.Column('sourceTimestampMs', sa.Integer(), nullable=True),
    sa.Column('sourceQuote', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'APPROVED', 'REJECTED', 'DEFERRED', 'EXECUTING', 'EXECUTED', 'FAILED', name='ActionStatus'), server_default=sa.text("'PROPOSED'"), nullable=False),
    sa.Column('executionResult', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('executionAttempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('executedAt', sa.DateTime(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('supersededById', sa.Text(), nullable=True),
    sa.Column('parentId', sa.Text(), nullable=True),
    sa.Column('stepOrder', sa.Integer(), nullable=True),
    sa.Column('dependsOnId', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dependsOnId'], ['ActionItem.id'], name=op.f('ActionItem_dependsOnId_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parentId'], ['ActionItem.id'], name=op.f('ActionItem_parentId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersededById'], ['ActionItem.id'], name=op.f('ActionItem_supersededById_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transcriptId'], ['Transcript.id'], name=op.f('ActionItem_transcriptId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ActionItem_pkey'))
    )
    op.create_index('ActionItem_ownerName_idx', 'ActionItem', ['ownerName'], unique=False)
    op.create_index('ActionItem_status_priority_deadline_idx', 'ActionItem', ['status', 'priority', 'deadline'], unique=False)
    op.create_index('ActionItem_transcriptId_status_idx', 'ActionItem', ['transcriptId', 'status'], unique=False)
    op.create_table('BrdRevision',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('documentId', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('spokenText', sa.Text(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changeSummary', sa.Text(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['documentId'], ['BrdDocument.id'], name=op.f('BrdRevision_documentId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('BrdRevision_pkey'))
    )
    op.create_index('BrdRevision_documentId_ordinal_idx', 'BrdRevision', ['documentId', 'ordinal'], unique=False)
    op.create_index('BrdRevision_documentId_ordinal_key', 'BrdRevision', ['documentId', 'ordinal'], unique=True)
    op.create_table('Decision',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('transcriptId', sa.Text(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('decidedBy', sa.Text(), nullable=True),
    sa.Column('sourceTimestampMs', sa.Integer(), nullable=True),
    sa.Column('sourceQuote', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transcriptId'], ['Transcript.id'], name=op.f('Decision_transcriptId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Decision_pkey'))
    )
    op.create_index('Decision_transcriptId_idx', 'Decision', ['transcriptId'], unique=False)
    op.create_table('Speaker',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('transcriptId', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('displayName', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['transcriptId'], ['Transcript.id'], name=op.f('Speaker_transcriptId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Speaker_pkey'))
    )
    op.create_index('Speaker_transcriptId_label_key', 'Speaker', ['transcriptId', 'label'], unique=True)
    op.create_table('TranscriptAsset',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('transcriptId', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('mimeType', sa.Text(), nullable=False),
    sa.Column('byteSize', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.Text(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transcriptId'], ['Transcript.id'], name=op.f('TranscriptAsset_transcriptId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('TranscriptAsset_pkey'))
    )
    op.create_index('TranscriptAsset_checksum_idx', 'TranscriptAsset', ['checksum'], unique=False)
    op.create_index('TranscriptAsset_transcriptId_key', 'TranscriptAsset', ['transcriptId'], unique=True)
    op.create_table('ApprovalRequest',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('actionItemId', sa.Text(), nullable=False),
    sa.Column('riskTier', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='RiskTier'), nullable=False),
    sa.Column('requiredGate', sa.Enum('AUTO', 'EXPLICIT_APPROVAL', 'EXPLICIT_APPROVAL_WITH_CONFIRMATION', name='ApprovalGate'), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='ApprovalState'), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('approverId', sa.Text(), nullable=True),
    sa.Column('decidedAt', sa.DateTime(), nullable=True),
    sa.Column('decisionNote', sa.Text(), nullable=True),
    sa.Column('presented', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expiresAt', sa.DateTime(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actionItemId'], ['ActionItem.id'], name=op.f('ApprovalRequest_actionItemId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approverId'], ['User.id'], name=op.f('ApprovalRequest_approverId_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('ApprovalRequest_pkey'))
    )
    op.create_index('ApprovalRequest_state_expiresAt_idx', 'ApprovalRequest', ['state', 'expiresAt'], unique=False)
    op.create_table('AuditLog',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actorType', sa.Enum('USER', 'SYSTEM', 'AGENT', name='ActorType'), server_default=sa.text("'USER'"), nullable=False),
    sa.Column('actorId', sa.Text(), nullable=True),
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('actionItemId', sa.Text(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requestId', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actionItemId'], ['ActionItem.id'], name=op.f('AuditLog_actionItemId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['actorId'], ['User.id'], name=op.f('AuditLog_actorId_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('AuditLog_pkey'))
    )
    op.create_index('AuditLog_actionItemId_at_idx', 'AuditLog', ['actionItemId', 'at'], unique=False)
    op.create_index('AuditLog_event_at_idx', 'AuditLog', ['event', 'at'], unique=False)
    op.create_table('Correction',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('actionItemId', sa.Text(), nullable=False),
    sa.Column('field', sa.Text(), nullable=False),
    sa.Column('beforeValue', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('afterValue', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('transcriptExcerpt', sa.Text(), nullable=True),
    sa.Column('correctedBy', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actionItemId'], ['ActionItem.id'], name=op.f('Correction_actionItemId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Correction_pkey'))
    )
    op.create_index('Correction_field_createdAt_idx', 'Correction', ['field', 'createdAt'], unique=False)
    op.create_table('ExecutionAttempt',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('actionItemId', sa.Text(), nullable=False),
    sa.Column('idempotencyKey', sa.Text(), nullable=False),
    sa.Column('attemptNumber', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Enum('RUNNING', 'SUCCESS', 'FAILED', 'SKIPPED', name='AttemptOutcome'), server_default=sa.text("'RUNNING'"), nullable=False),
    sa.Column('externalId', sa.Text(), nullable=True),
    sa.Column('externalUrl', sa.Text(), nullable=True),
    sa.Column('errorCode', sa.Text(), nullable=True),
    sa.Column('errorMessage', sa.Text(), nullable=True),
    sa.Column('durationMs', sa.Integer(), nullable=True),
    sa.Column('startedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finishedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actionItemId'], ['ActionItem.id'], name=op.f('ExecutionAttempt_actionItemId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ExecutionAttempt_pkey'))
    )
    op.create_index('ExecutionAttempt_actionItemId_idempotencyKey_attemptNumber_key', 'ExecutionAttempt', ['actionItemId', 'idempotencyKey', 'attemptNumber'], unique=True)
    op.create_index('ExecutionAttempt_idempotencyKey_outcome_idx', 'ExecutionAttempt', ['idempotencyKey', 'outcome'], unique=False)
    op.create_table('Segment',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('transcriptId', sa.Text(), nullable=False),
    sa.Column('speakerId', sa.Text(), nullable=True),
    sa.Column('startMs', sa.Integer(), nullable=False),
    sa.Column('endMs', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['speakerId'], ['Speaker.id'], name=op.f('Segment_speakerId_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transcriptId'], ['Transcript.id'], name=op.f('Segment_transcriptId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Segment_pkey'))
    )
    op.create_index('Segment_transcriptId_startMs_idx', 'Segment', ['transcriptId', 'startMs'], unique=False)
    op.create_table('Word',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('segmentId', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('startMs', sa.Integer(), nullable=False),
    sa.Column('endMs', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['segmentId'], ['Segment.id'], name=op.f('Word_segmentId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Word_pkey'))
    )
    op.create_index('Word_segmentId_startMs_idx', 'Word', ['segmentId', 'startMs'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('Word_segmentId_startMs_idx', table_name='Word')
    op.drop_table('Word')
    op.drop_index('Segment_transcriptId_startMs_idx', table_name='Segment')
    op.drop_table('Segment')
    op.drop_index('ExecutionAttempt_idempotencyKey_outcome_idx', table_name='ExecutionAttempt')
    op.drop_index('ExecutionAttempt_actionItemId_idempotencyKey_attemptNumber_key', table_name='ExecutionAttempt')
    op.drop_table('ExecutionAttempt')
    op.drop_index('Correction_field_createdAt_idx', table_name='Correction')
    op.drop_table('Correction')
    op.drop_index('AuditLog_event_at_idx', table_name='AuditLog')
    op.drop_index('AuditLog_actionItemId_at_idx', table_name='AuditLog')
    op.drop_table('AuditLog')
    op.drop_index('ApprovalRequest_state_expiresAt_idx', table_name='ApprovalRequest')
    op.drop_table('ApprovalRequest')
    op.drop_index('TranscriptAsset_transcriptId_key', table_name='TranscriptAsset')
    op.drop_index('TranscriptAsset_checksum_idx', table_name='TranscriptAsset')
    op.drop_table('TranscriptAsset')
    op.drop_index('Speaker_transcriptId_label_key', table_name='Speaker')
    op.drop_table('Speaker')
    op.drop_index('Decision_transcriptId_idx', table_name='Decision')
    op.drop_table('Decision')
    op.drop_index('BrdRevision_documentId_ordinal_key', table_name='BrdRevision')
    op.drop_index('BrdRevision_documentId_ordinal_idx', table_name='BrdRevision')
    op.drop_table('BrdRevision')
    op.drop_index('ActionItem_transcriptId_status_idx', table_name='ActionItem')
    op.drop_index('ActionItem_status_priority_deadline_idx', table_name='ActionItem')
    op.drop_index('ActionItem_ownerName_idx', table_name='ActionItem')
    op.drop_table('ActionItem')
    op.drop_index('UserSettings_userId_key', table_name='UserSettings')
    op.drop_table('UserSettings')
    op.drop_index('Transcript_userId_status_idx', table_name='Transcript')
    op.drop_index('Transcript_userId_createdAt_idx', table_name='Transcript')
    op.drop_table('Transcript')
    op.drop_index('TeamMember_userId_name_idx', table_name='TeamMember')
    op.drop_index('TeamMember_userId_email_key', table_name='TeamMember')
    op.drop_table('TeamMember')
    op.drop_index('PasswordResetToken_userId_createdAt_idx', table_name='PasswordResetToken')
    op.drop_index('PasswordResetToken_tokenHash_key', table_name='PasswordResetToken')
    op.drop_index('PasswordResetToken_expiresAt_idx', table_name='PasswordResetToken')
    op.drop_table('PasswordResetToken')
    op.drop_index('IntegrationAccount_userId_provider_key', table_name='IntegrationAccount')
    op.drop_table('IntegrationAccount')
    op.drop_index('Credential_userId_service_key', table_name='Credential')
    op.drop_index('Credential_userId_module_idx', table_name='Credential')
    op.drop_table('Credential')
    op.drop_index('CalendarBusyBlock_userId_startsAt_idx', table_name='CalendarBusyBlock')
    op.drop_table('CalendarBusyBlock')
    op.drop_index('BrdDocument_userId_createdAt_idx', table_name='BrdDocument')
    op.drop_table('BrdDocument')
    op.drop_index('AuthIdentity_userId_idx', table_name='AuthIdentity')
    op.drop_index('AuthIdentity_provider_providerAccountId_key', table_name='AuthIdentity')
    op.drop_table('AuthIdentity')
    op.drop_index('User_email_key', table_name='User')
    op.drop_table('User')
    op.drop_index('OAuthState_expiresAt_idx', table_name='OAuthState')
    op.drop_table('OAuthState')
    # ### end Alembic commands ###
